version: '3.8'

services:
  n8n:
    # Use a imagem oficial do n8n
    image: n8nio/n8n
    restart: always
    container_name: n8n_api

    ports:
      - 5678:5678
      
    environment:
      N8N_HOST: localhost:5678
      N8N_PROTOCOL: http
      WEBHOOK_URL: http://localhost:5678
      N8N_LOG_LEVEL: info
      
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: