version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app/app
    env_file:
      - .env
    command: nodemon app/server.js
