FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

# segunda etapa — imagem final e leve
FROM node:22-alpine

WORKDIR /app

COPY --from=builder /app ./

CMD ["node", "exercicio-04.js"]
