FROM node:22-alpine

# cria o diretório
WORKDIR /app

# copia package.json e package-lock.json
COPY package*.json ./

# instala dependências
RUN npm install

# copia os arquivos
COPY . .

# expõe uma porta
EXPOSE 3000

CMD ["node", "exercicio-03.js"]
